CREATE TABLE `PiCOS-userdata` 
(
    `PCOS (Y/N)`	tinyint(1),
    `BMI`	float,
    `Blood Group`	INT,
    `Cycle(R/I)`	INT,
    `Marraige Status (Yrs)`	INT,
    `Pregnant(Y/N)`	tinyint(1),
    `No. of aborptions`	tinyint(1),
    `Waist:Hip Ratio`	float,
    `Weight gain(Y/N)`	tinyint(1),
    `hair growth(Y/N)`	tinyint(1),
    `Skin darkening (Y/N)`	tinyint(1),
    `Hair loss(Y/N)`	tinyint(1),
    `Pimples(Y/N)`	tinyint(1),
    `Fast food (Y/N)`	tinyint(1),
    `Reg.Exercise(Y/N)`	tinyint(1),
    `age_category`	INT,
    `marriage_category`	tinyint(1),
);